##not using this code, but will be cleaner if I do...generated it to go through the bacterial samples

  <!-- temp <- read_excel(files[idx], .name_repair = ~make.unique(.x, sep = "_")) #only 2+ instance is renamed -->
  <!-- #will always be a row with cast = 0: use that to find the number of header lines -->
  <!-- h = which(temp[,1]==0 | is.na(temp[,1])) #have both 0 and NA -->
  <!-- headerToSkip <- (h) - 1 -->
  <!-- one <- read_excel(files[idx], skip=headerToSkip,.name_repair = ~make.unique(.x, sep = "_")) #only 2+ instance is renamed -->

  <!-- #only keep to the second instance of Nisken/Niskin/nisken/niskin -->
  <!-- n <- which((one=="Niskin" | one=="Nisken" | one=="niskin" | one=="nisken"),arr.ind=TRUE) -->

  <!-- if (rlang::is_empty(n)) { -->

  <!--   #don't have the duplicated last row, search colnames for the second Niskin -->
  <!--   v <- tolower(colnames(one)) -->
  <!--   rightSide <- which(grepl("nisk",v))[2] -->
  <!--   one <- one[,-rightSide] -->
  <!--   rm(v,rightSide) -->

  <!-- } else { -->
  <!--   bottomRow <- max(n[,'row']) -->
  <!--   rightSide <- max(n[,'col']) -->
  <!--   #remove last row (BATS repeats information) -->
  <!--   one <- one[-bottomRow,] -->

  <!--   #also delete the second Niskin column -->
  <!--   #only keep to rightSide - 1 -->
  <!--   one <- one[,1: (rightSide-1) ]    -->
  <!--   rm(bottomRow,rightSide) -->
  <!-- } -->


  <!-- one <- one %>% mutate(across(everything(), as.character)) -->


---
title: "BATS_sampling"
author: "Krista Longnecker"
date: "`28 May 2026`"
output: html_notebook
---


```{r load_libraries, message=FALSE, warning=FALSE}
rm(list = ls()) #start with a clean workspace (better for testing)

library(data.table) # you need to install this package from CRAN
library(dplyr)
library(readr) #this is part of the tidyverse package
library(here) #install this (once, install.packages("here))
#library(tidyverse) #amazing 
library(lubridate) #great for handling date data

# library(reshape2)
# library(MBA)
# library(mgcv)
# library(marmap)
# library(FNN)

library(readxl) #reading excel files
library(purrr)
#library(hms) #for time data
library(writexl)#Use the following to install castr if it doesnt load above.  See here for details https://rdrr.io/github/jiho/castr/
#install.packages("remotes")
#remotes::install_github("jiho/castr")
#library(castr)
```




```{r findDatafiles, message =FALSE}
baseDir = "D:/Dropbox/GitHub_niskin/data_pipeline/R_code"
# Define the path to the data file
wDir <- "../RawData/BATS & HS CAST SHEETS"

# #three folders in there for BATS, BVal, and HS
# bvalDir <- "BVal Cast Sheets"
# wPath <- paste0(wDir,"/",bvalDir)
# files <- list.files(path = wDir,recursive = TRUE, full.names = TRUE)

#sometimes there is a file labeled 'BIOS-SCOPE', other times there are just individual cast files that are relevant.
#start by pulling information from any file labeled 'BIOS-SCOPE'
patterns <- c("BIOS-SCOPE","H-R DOM","HR_DOM") #some files with a different extension (cruise 10323 and 61319)
possible <- paste(patterns,collapse="|")
files <- list.files(path = wDir,pattern = possible,recursive = TRUE, full.names = TRUE)


```


```{r doFirstFile}
#turns out BATS has a sample type that is listed as a number. Will be easier to 
#merge on that because the names change from sheet to sheet. I will need to confirm
#that I have guess right about the numbers.

#start with Luis's DNA. I think this is sample number eDNA (number 160)  
#use the first file to set up the dataframe...
idx <- 1
one <- read_excel(files[idx], skip=1,.name_repair = ~make.unique(.x, sep = "_")) #only 2+ instance is renamed
one <- one %>% mutate(across(everything(), as.character))

#remove last row (BATS repeats information)
one <- one[-nrow(one),]

#also delete the second Niskin column, this will get most but not all
one <- one[,-ncol(one)]

#add all cast information from the file...need some error checking
# (tidyup names...spelling and match to names/numbers for BIOS-SCOPE samples)
#make all the names lower case as a start
colnames(one) <- tolower(colnames(one))

#definitely a better way to do this, but I am running out of steam
colnames(one) <- gsub("% cast","cruise_cast",colnames(one))
colnames(one) <- gsub("%cast","cruise_cast",colnames(one))
colnames(one) <- gsub("nisken","niskin",colnames(one))
colnames(one) <- gsub("niskin","niskin",colnames(one))

# BATS puts ## of sample type in different row, but that is the one that should match across cruises...
# search for the number and add to column names in main sheet if it does not already exist
k <- which (one[1,] > 0) 

# # keep the headers that correspond to the numbers, use this information to backtrack as needed
# one$sampleNames = colnames(one)[k]

# inefficient, but how my brain is thinking today
# iterate through all the columns with a number...make a column name if is does not exist
for (idx2 in 1:length(k)) {
  #colnames(one)[k][idx2] <- paste0(colnames(one)[k][idx2],"_",as.character(one[1,k[idx2]])) 
  colnames(one)[k][idx2] <- paste0(as.character(one[1,k[idx2]]) ,"_",colnames(one)[k][idx2]) 
}

#parse cast information into cruise/cast/niskin
one$cruise = substr(as.character(one$cruise_cast),1,5)
one <- one %>% relocate(cruise,.after = cruise_cast)
one$cast = substr(as.character(one$cruise_cast),6,8)
one <- one %>% relocate(cast,.after = cruise)

#now put cruise / cast in row that is zero, use for sorting later
one[1,'cast'] <- one[2,'cast']
one[1,'cruise'] <- one[2,'cruise']

df <- one
rm(one)


```

```{r doRestFiles}

#start with 2 because files[1] was used to setup the matrix

for (idx in 2:length(files)) {
  #idx <- 116
  one <- read_excel(files[idx], skip=1,.name_repair = ~make.unique(.x, sep = "_")) #only 2+ instance is renamed
  #need to make sure there are no empty column names...this happens when the excel file has empty columns...
  colnames(one)[colnames(one) == "" ] <- "empty"
  one <- one %>% mutate(across(everything(), as.character))
  
  #remove last row (BATS repeats information)
  one <- one[-nrow(one),]
  
  #add all cast information from the file...need some error checking
  # (tidyup names...spelling and match to names/numbers for BIOS-SCOPE samples)
  #make all the names lower case as a start
  colnames(one) <- tolower(colnames(one))
  
  #definitely a better way to do this, but I am running out of steam
  colnames(one) <- gsub("% cast","cruise_cast",colnames(one))
  colnames(one) <- gsub("%cast","cruise_cast",colnames(one))
  colnames(one) <- gsub("nisken","niskin",colnames(one))
  colnames(one) <- gsub("niskin","niskin",colnames(one))
  
  # BATS puts ## of sample type in different row, but that is the one that should match across cruises...
  # search for the number and add to column names in main sheet if it does not already exist
  k <- which (one[1,] > 0) 
  
  # super inefficient, but how my brain is thinking today
  # iterate through all the columns with a number...make a column name if is does not exist
  for (idx2 in 1:length(k)) {
    #colnames(one)[k][idx2] <- paste0(colnames(one)[k][idx2],"_",as.character(one[1,k[idx2]])) 
    colnames(one)[k][idx2] <- paste0(as.character(one[1,k[idx2]]) ,"_",colnames(one)[k][idx2]) 
  }
  
  #parse cast information into cruise/cast/niskin
  one$cruise = substr(as.character(one$cruise_cast),1,5)
  one <- one %>% relocate(cruise,.after = cruise_cast)
  one$cast = substr(as.character(one$cruise_cast),6,8)
  one <- one %>% relocate(cast,.after = cruise)

  #now put cruise / cast in row that is zero, use for sorting later
  one[1,'cast'] <- one[2,'cast']
  one[1,'cruise'] <- one[2,'cruise']
  
  
  df <- bind_rows(df,one)
  rm(one)
  
}


```


```{r getUnique}


# #any row with cast ==0 will be the sample types number, find those and get a list of unique options
# m <- which(df[,'cruise_cast'] ==0 )
# dfu <- unique(df[m,])
# dfu <- dfu[,order(colnames(dfu))]
# dfu <- dfu %>% relocate(cast)
# dfu <- dfu %>% relocate(cruise)
# 
# #tidy up and delete the empty columns
# dfu <- dfu[, colSums(is.na(dfu)) < nrow(dfu)]
# write_xlsx(dfu,'../RawData/BIOSSCOPE_uniqueSampleTypes.xlsx')


#also tidy up the df with the sample numbers
df <- df[,order(colnames(df))]
#only keep rows where Cruise_cast is not zero or NA
df <- df[df$cruise_cast != 0,]
df <- df[!is.na(df$cruise_cast),]

df <- df %>% relocate(flag)
df <- df %>% relocate(depth)
df <- df %>% relocate(niskin)
df <- df %>% relocate(cast)
df <- df %>% relocate(cruise)
df <- df[, colSums(is.na(df)) < nrow(df)]
#remove zeros
df[df==0] <- NA

#count how many samples of each type were collected
#change  0 to NA
df_counts <- as.data.frame(colSums(df>0,na.rm=TRUE))
df_counts$row_names <- rownames(df_counts)

```


```{r}


write_xlsx(df_counts,'../RawData/counts.xlsx')
write_xlsx(df,'../RawData/BIOSSCOPE_BATSsamples_to2024.xlsx')

```


